accounts/urls.py
from django.urls import path
from .views import RegisterView, LoginView, logout_view
app_name= "accounts"
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
]

taskmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from tasks.views import TaskListView,ContactView,AboutView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tasks/', include('tasks.urls')),
    path('', TaskListView.as_view(),name="homepage"),
    path('contact', ContactView.as_view(),name="contact"),
    path('about', AboutView.as_view(),name="about"),

]

tasks/urls.py
from django.urls import path
from .views import TaskListView, TaskCreateView, TaskUpdateView, TaskDeleteView
app_name= "tasks"
urlpatterns = [
    path('', TaskListView.as_view(), name='task-list'),
    path('add/', TaskCreateView.as_view(), name='task-add'),
    path('<int:pk>/edit/', TaskUpdateView.as_view(), name='task-edit'),
    path('<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
]

accounts/models.py
from django.db import models

# Create your models here.
# 
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

tasks/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    due_date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

accounts/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm
class SignUpForm(UserCreationForm):
#profile_year        = blaaa blaa blaaa irrelevant.. You have your own stuff here don't worry about it
   # here is the important part.. add a class Meta-
   class Meta:
      model = User #this is the "YourCustomUser" that you imported at the top of the file  
      fields = ('username', 'password1', 'password2')

class Login(UserCreationForm):
#profile_year        = blaaa blaa blaaa irrelevant.. You have your own stuff here don't worry about it
   # here is the important part.. add a class Meta-
   class Meta:
      model = User #this is the "YourCustomUser" that you imported at the top of the file  
      fields = ('username', 'password1')     

tasks/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'due_date']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views import View
from .forms import SignUpForm
class RegisterView(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, 'accounts/register.html', {'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)

            return redirect('tasks:task-list')
        else:
            print(form.errors)

 
        return render(request, 'accounts/register.html', {'form': form})

class LoginView(View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, 'accounts/login.html', {'form': form})

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('tasks:task-list')
        return render(request, 'accounts/login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('accounts:login')

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import View
from .models import Task
from .forms import TaskForm
from django.views.generic.base import TemplateView
@method_decorator(login_required, name='dispatch')
class TaskListView(View):
    def get(self, request):
        tasks = Task.objects.filter(user=request.user).order_by('due_date')
        return render(request, 'tasks/task_list.html', {'tasks': tasks})

@method_decorator(login_required, name='dispatch')
class TaskCreateView(View):
    def get(self, request):
        form = TaskForm()
        return render(request, 'tasks/add_task.html', {'form': form})

    def post(self, request):
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect('tasks:task-list')
        return render(request, 'tasks/add_task.html', {'form': form})

@method_decorator(login_required, name='dispatch')
class TaskUpdateView(View):
    def get(self, request, pk):
        task = get_object_or_404(Task, pk=pk, user=request.user)
        form = TaskForm(instance=task)
        return render(request, 'tasks/add_task.html', {'form': form})

    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk, user=request.user)
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('tasks:task-list')
        return render(request, 'tasks/add_task.html', {'form': form})

@method_decorator(login_required, name='dispatch')
class TaskDeleteView(View):
    def post(self, request, pk):
        task = get_object_or_404(Task, pk=pk, user=request.user)
        task.delete()
        return redirect('tasks:task-list')
class AboutView(TemplateView):
    template_name = 'about.html'

class ContactView(TemplateView):
    template_name = 'contact.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{%load static%}
{% block header %}

<header class="masthead" style="background-image: url({%static 'assets/img/home-bg.jpg'%})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Welcome back</h1>
                            <span class="subheading">Log in to continue</span>
                            <form class="site-form" method="post" action="{%url 'accounts:login' %}">
                                {% csrf_token %}
                                {{ form.as_p }}
    <input type="hidden" name="next" value="{{request.GET.next}}">
    <div class="form-group">
        <button class="btn btn-primary"  type="submit">Login</button>
    </div>
    </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>


{% endblock %}

accounts/templates/accounts/register.html
{%extends 'base.html'%}
{%load static%}
{%block header%}
<header class="masthead" style="background-image: url({%static 'assets/img/home-bg.jpg'%})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="site-heading">
                            <h1>Welcome to Taskify</h1>
                            <span class="subheading">Register to continue</span>
                            <form class="site-form" method="post" action="{%url 'accounts:register' %}">
        {% csrf_token %}
        {{ form.as_table }}

        <button class="btn btn-primary"  type="submit">Register</button>
    </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>
{%endblock%}

{%block content%}

{%endblock%}

tasks/templates/tasks/add_task.html
{% extends 'base.html' %}
{%load static%}
{% block header %}<header class="masthead" style="background-image: url({%static 'assets/img/home-bg.jpg'%})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Taskify</h1>
                    <span class="subheading"></span>
                </div>
            </div>
        </div>
    </div>
</header>{% endblock %}

{% block extra_css %}
    <!-- Additional CSS specific to this template if needed -->
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-4">Add a New Task</h2>
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_title">Title</label>
                    <input type="text" class="form-control" id="id_title" name="title" placeholder="Enter task title">
                </div>
                <div class="form-group">
                    <label for="id_description">Description</label>
                    <textarea class="form-control" id="id_description" name="description" rows="3" placeholder="Enter task description"></textarea>
                </div>
                <div class="form-group">
                    <label for="id_due_date">Due Date</label>
                    <input type="date" class="form-control" id="id_due_date" name="due_date">
                </div>
                <button type="submit" class="btn btn-primary btn-block">Add Task</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

tasks/templates/tasks/task_list.html
{% extends 'base.html' %}
{%load static%}
{%block header%}
 <header class="masthead" style="background-image: url({%static 'assets/img/home-bg.jpg'%})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>Your Tasks</h1>
                    <span class="subheading">Complete them soon</span>
                </div>
            </div>
        </div>
    </div>
</header>{%endblock%}

{% block content %}
<div class="container mt-5">
  
    <h2><button onclick="window.location.href='{% url 'tasks:task-add' %}'" class="btn btn-primary mt-3">Add Task</button></h2>
    
   
    <ul class="list-group mt-3">
        {% for task in tasks %}
        <li class="list-group-item">
            <h5>{{ task.title }}</h5>
            <p>{{ task.description }}</p>
            <p>Due date: {{ task.due_date }}</p>
            <a href="{% url 'tasks:task-edit' task.id %}" class="btn btn-info">Edit</a>
            <form method="post" action="{% url 'tasks:task-delete' task.id %}" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </li>
        {% endfor %}
    </ul>
    
</div>
{% endblock %}

templates/about.html
{%extends 'base.html'%}
{%load static%}
<!-- Page Header-->
{%block header%}<header class="masthead" style="background-image: url({%static 'assets/img/home-bg.jpg'%})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>About Me</h1>
                            <span class="subheading">This is what I do.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>{%endblock%}
<!-- Main Content-->
{%block content%}<main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                    </div>
                </div>
            </div>
        </main>{%endblock%}
<!-- Footer-->

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Task Management</title>
        {% load static %}
        <link rel="icon" type="image/x-icon" href=" {% static 'assets/favicon.ico' %} " />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->

        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <style>
        /* Styles for form container */

    </style>
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{%url 'homepage'%}">Taskify</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'homepage' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'about'%}">About</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'contact'%}">Contact</a></li>
                        {%if user.is_authenticated%}
                        <li class="nav-item">
                            <form class="nav-link px-lg-3 py-3 py-lg-4"  method="post" action="{%url 'accounts:logout' %}">
                                {% csrf_token %}
                                <button class="logout"  type="submit"><svg height="32" viewBox="0 0 32 32" width="32" xmlns="http://www.w3.org/2000/svg"><path d="m6 30h12a2.0023 2.0023 0 0 0 2-2v-3h-2v3h-12v-24h12v3h2v-3a2.0023 2.0023 0 0 0 -2-2h-12a2.0023 2.0023 0 0 0 -2 2v24a2.0023 2.0023 0 0 0 2 2z"/><path d="m20.586 20.586 3.586-3.586h-14.172v-2h14.172l-3.586-3.586 1.414-1.414 6 6-6 6z"/><path d="m0 0h32v32h-32z" fill="none"/></svg>Log out</button>
                            </form>
                        </li>
                        {%else%}
                        <li class="nav-item">
                          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                           <a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'accounts:register'%}">Get Started</a>
                        </li>
                        {%endif%}
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
           {%block header%}{%endblock%}
        <!-- Main Content-->
           {%block content%}{%endblock%}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/contact.html
{%extends 'base.html'%}
{%load static%}
<!-- Page Header-->
{%block header%} <header class="masthead" style="background-image: url({%static 'assets/img/home-bg.jpg'%})">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>Contact Me</h1>
                            <span class="subheading">Have questions? I have answers.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>{%endblock%}
<!-- Main Content-->
{%block content%}<main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                        <div class="my-5">
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                                <div class="form-floating">
                                    <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                                    <label for="name">Name</label>
                                    <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="email" type="email" placeholder="Enter your email..." data-sb-validations="required,email" />
                                    <label for="email">Email address</label>
                                    <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                    <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                                </div>
                                <div class="form-floating">
                                    <input class="form-control" id="phone" type="tel" placeholder="Enter your phone number..." data-sb-validations="required" />
                                    <label for="phone">Phone Number</label>
                                    <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                                </div>
                                <div class="form-floating">
                                    <textarea class="form-control" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                                    <label for="message">Message</label>
                                    <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                                </div>
                                <br />
                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <div class="d-none" id="submitSuccessMessage">
                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                        To activate this form, sign up at
                                        <br />
                                        <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                    </div>
                                </div>
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                <!-- Submit Button-->
                                <button class="btn btn-primary text-uppercase disabled" id="submitButton" type="submit">Send</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>{%endblock%}
<!-- Footer-->